apiVersion: v1
kind: Pod
metadata:
  name: init-container-test
spec:
  containers:
    - name: displayer-container
      image: busybox:stable
  initContainers:
    - name: init-container
      image: busybox:stable
