apiVersion: batch/v1
kind: Job
metadata:
  name: deadline-printer-job
spec:
  template:
    spec:
      containers:
      - name: deadline-printer
        image: busybox:stable
        command: ['/bin/sh', '-c']
        args:
        - echo "Hello from the deadline printer :)!! I'll be be sleeping for 12 seconds now";
          sleep 8;
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 10

